development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://rediscloud:N9f98T9SzN1mIadL@redis-18363.c10.us-east-1-3.ec2.cloud.redislabs.com:18363
  channel_prefix: DevcampPortfolio_production
